# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 02:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dbase', '0002_auto_20161217_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 18, 2, 28, 23, 451955, tzinfo=utc), verbose_name='location time'),
            preserve_default=False,
        ),
    ]
